drop extension if exists "pg_net";


  create table "public"."collage" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "uni_id" uuid default gen_random_uuid(),
    "name" text,
    "metadata" jsonb
      );



  create table "public"."course" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "length" numeric
      );



  create table "public"."department" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "collage_id" uuid,
    "uni_id" uuid,
    "name" text
      );



  create table "public"."university" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "metadata" jsonb
      );


CREATE UNIQUE INDEX collage_pkey ON public.collage USING btree (id);

CREATE UNIQUE INDEX course_pkey ON public.course USING btree (id);

CREATE UNIQUE INDEX department_pkey ON public.department USING btree (id);

CREATE UNIQUE INDEX university_pkey ON public.university USING btree (id);

alter table "public"."collage" add constraint "collage_pkey" PRIMARY KEY using index "collage_pkey";

alter table "public"."course" add constraint "course_pkey" PRIMARY KEY using index "course_pkey";

alter table "public"."department" add constraint "department_pkey" PRIMARY KEY using index "department_pkey";

alter table "public"."university" add constraint "university_pkey" PRIMARY KEY using index "university_pkey";

alter table "public"."collage" add constraint "collage_uni_id_fkey" FOREIGN KEY (uni_id) REFERENCES university(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collage" validate constraint "collage_uni_id_fkey";

alter table "public"."department" add constraint "department_collage_id_fkey" FOREIGN KEY (collage_id) REFERENCES collage(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."department" validate constraint "department_collage_id_fkey";

alter table "public"."department" add constraint "department_uni_id_fkey" FOREIGN KEY (uni_id) REFERENCES university(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."department" validate constraint "department_uni_id_fkey";

grant delete on table "public"."collage" to "anon";

grant insert on table "public"."collage" to "anon";

grant references on table "public"."collage" to "anon";

grant select on table "public"."collage" to "anon";

grant trigger on table "public"."collage" to "anon";

grant truncate on table "public"."collage" to "anon";

grant update on table "public"."collage" to "anon";

grant delete on table "public"."collage" to "authenticated";

grant insert on table "public"."collage" to "authenticated";

grant references on table "public"."collage" to "authenticated";

grant select on table "public"."collage" to "authenticated";

grant trigger on table "public"."collage" to "authenticated";

grant truncate on table "public"."collage" to "authenticated";

grant update on table "public"."collage" to "authenticated";

grant delete on table "public"."collage" to "service_role";

grant insert on table "public"."collage" to "service_role";

grant references on table "public"."collage" to "service_role";

grant select on table "public"."collage" to "service_role";

grant trigger on table "public"."collage" to "service_role";

grant truncate on table "public"."collage" to "service_role";

grant update on table "public"."collage" to "service_role";

grant delete on table "public"."course" to "anon";

grant insert on table "public"."course" to "anon";

grant references on table "public"."course" to "anon";

grant select on table "public"."course" to "anon";

grant trigger on table "public"."course" to "anon";

grant truncate on table "public"."course" to "anon";

grant update on table "public"."course" to "anon";

grant delete on table "public"."course" to "authenticated";

grant insert on table "public"."course" to "authenticated";

grant references on table "public"."course" to "authenticated";

grant select on table "public"."course" to "authenticated";

grant trigger on table "public"."course" to "authenticated";

grant truncate on table "public"."course" to "authenticated";

grant update on table "public"."course" to "authenticated";

grant delete on table "public"."course" to "service_role";

grant insert on table "public"."course" to "service_role";

grant references on table "public"."course" to "service_role";

grant select on table "public"."course" to "service_role";

grant trigger on table "public"."course" to "service_role";

grant truncate on table "public"."course" to "service_role";

grant update on table "public"."course" to "service_role";

grant delete on table "public"."department" to "anon";

grant insert on table "public"."department" to "anon";

grant references on table "public"."department" to "anon";

grant select on table "public"."department" to "anon";

grant trigger on table "public"."department" to "anon";

grant truncate on table "public"."department" to "anon";

grant update on table "public"."department" to "anon";

grant delete on table "public"."department" to "authenticated";

grant insert on table "public"."department" to "authenticated";

grant references on table "public"."department" to "authenticated";

grant select on table "public"."department" to "authenticated";

grant trigger on table "public"."department" to "authenticated";

grant truncate on table "public"."department" to "authenticated";

grant update on table "public"."department" to "authenticated";

grant delete on table "public"."department" to "service_role";

grant insert on table "public"."department" to "service_role";

grant references on table "public"."department" to "service_role";

grant select on table "public"."department" to "service_role";

grant trigger on table "public"."department" to "service_role";

grant truncate on table "public"."department" to "service_role";

grant update on table "public"."department" to "service_role";

grant delete on table "public"."university" to "anon";

grant insert on table "public"."university" to "anon";

grant references on table "public"."university" to "anon";

grant select on table "public"."university" to "anon";

grant trigger on table "public"."university" to "anon";

grant truncate on table "public"."university" to "anon";

grant update on table "public"."university" to "anon";

grant delete on table "public"."university" to "authenticated";

grant insert on table "public"."university" to "authenticated";

grant references on table "public"."university" to "authenticated";

grant select on table "public"."university" to "authenticated";

grant trigger on table "public"."university" to "authenticated";

grant truncate on table "public"."university" to "authenticated";

grant update on table "public"."university" to "authenticated";

grant delete on table "public"."university" to "service_role";

grant insert on table "public"."university" to "service_role";

grant references on table "public"."university" to "service_role";

grant select on table "public"."university" to "service_role";

grant trigger on table "public"."university" to "service_role";

grant truncate on table "public"."university" to "service_role";

grant update on table "public"."university" to "service_role";


