name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node & PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Setup Turborepo Remote Cache
      #   run: npx turbo link --token=${{ secrets.TURBO_TOKEN }}
      #   env:
      #     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #     TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Run tests
        run: pnpm test

      - name: Run e2e 
        run: pnpm e2e
